spring.datasource:
                  url: jdbc:mysql://localhost:3306/restaurantdb?createDatabaseIfNotExist = true&allowPublicKeyRetrieval = true&useSSL = false
                  username: root
                  password: root
                  driver-class-name: com.mysql.cj.jdbc.Driver
                  initialization-mode: always

spring.jpa:
           properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
           hibernate.use-new-id-generator-mappings: false
           hibernate.ddl-auto: update
           
# App Properties

apps:
    jwtSecret:  jwtsecret
    jwtExpirationMs:  86400000




#spring.profiles.active: dev


#logging configuration
logging.file: Logs/qa.log
           